const baseRoute = '/multiplatform-web';
export const eBayPublish = [{
  id: null,
  icon: "eBay",
  key: "EBAY_eBay",
  route: null,
  platform: "EBAY",
  apiPath: null,
  description: "EBay",
  typeStyle: "menu",
  parentKey: 'PLAT_Publish',
  children: [
    {
      id: null,
      icon: "publication",
      key: "EBAY_publish",
      route: "",
      platform: "EBAY",
      apiPath: null,
      description: "刊登",
      typeStyle: "menu",
      parentKey: "EBAY_eBay",
      children: [
        {
          id: null,
          key: "PLAT_EBAY_pubEBayGoodsInfo",
          route: baseRoute + "/pubEBayGoodsInfo",
          platform: "EBAY",
          apiPath: null,
          description: "商品资料",
          typeStyle: "menu",
          parentKey: "EBAY_publish",
          children: [],
        },

        {
          id: null,
          key: "PLAT_EBAY_pubEBayDraft",
          route: baseRoute + "/pubEBayDraft",
          platform: "EBAY",
          apiPath: null,
          description: "刊登草稿",
          typeStyle: "menu",
          parentKey: "EBAY_publish",
          children: [
            {
              id: null,
              typeStyle: "btn",
              key: "EBAY_pubEBayDraft-view",
              route: baseRoute + "/",
              platform: "EBAY",
              apiPath: null,
              description: "查看",
              parentKey: "PLAT_EBAY_pubEBayDraft",
              buttonType: "view"
            }
          ],
        },
        {
          id: null,
          key: "PLAT_EBAY_pubEBayVideoLibrary",
          route: baseRoute + "/pubEBayVideoLibrary",
          platform: "EBAY",
          apiPath: null,
          description: "视频库",
          typeStyle: "menu",
          parentKey: "EBAY_publish",
          children: [
            {
              id: null,
              typeStyle: "btn",
              key: "EBAY_pubEBayVideoLibrary-view",
              route: baseRoute + "/",
              platform: "EBAY",
              apiPath: null,
              description: "查看",
              parentKey: "PLAT_EBAY_pubEBayVideoLibrary",
              buttonType: "view"
            },
          ],
        },
        {
          id: null,
          key: "PLAT_EBAY_pubEBayOnLineGoods",
          route: baseRoute + "/pubEBayOnLineGoods",
          platform: "EBAY",
          apiPath: null,
          description: "刊登在线商品",
          typeStyle: "menu",
          parentKey: "EBAY_publish",
          children: [
            {
              id: null,
              typeStyle: "btn",
              key: "EBAY_pubEBayOnLineGoods-view",
              route: "",
              platform: "EBAY",
              apiPath: null,
              description: "查看",
              parentKey: "PLAT_EBAY_pubEBayOnLineGoods",
              buttonType: "view"
            },
            {
              id: null,
              typeStyle: "btn",
              key: "EBAY_pubEBayOnLineGoods-add",
              route: "",
              platform: "EBAY",
              apiPath: null,
              description: "新增按钮",
              parentKey: "EBAY_pubEBayOnLineGoods",
              buttonType: "add"
            },
            {
              id: null,
              typeStyle: "btn",
              key: "EBAY_pubEBayOnLineGoods-delete",
              route: "",
              platform: "EBAY",
              apiPath: null,
              description: "删除按钮",
              parentKey: "EBAY_pubEBayOnLineGoods",
              buttonType: "delete"
            }
          ],
        },

      ],
    },
    {
      id: null,
      icon: "template",
      key: "EBAY_eBayBoard",
      route: "",
      platform: "EBAY",
      apiPath: null,
      description: "模板",
      typeStyle: "menu",
      parentKey: "EBAY_eBay",
      children: [
        {
          id: null,
          typeStyle: "page",
          key: "PLAT_EBAY_pubEBayBoard",
          route: baseRoute + "/pubEBayBoard",
          platform: "EBAY",
          apiPath: null,
          description: "刊登通用模板",
          parentKey: "EBAY_eBayBoard",
          children: [{
            id: null,
            typeStyle: "btn",
            key: "EBAY_pubEBayBoard-view",
            route: "",
            platform: "EBAY",
            apiPath: null,
            description: "控制当前页面能否查看",
            parentKey: "PLAT_EBAY_pubEBayBoard",
            buttonType: "view"
          }, {
            id: null,
            typeStyle: "btn",
            key: "EBAY_pubEBayBoard-view",
            route: "",
            platform: "EBAY",
            apiPath: null,
            description: "编辑按钮",
            parentKey: "EBAY_pubEBayBoard",
            buttonType: "edit"
          }, {
            id: null,
            typeStyle: "btn",
            key: "EBAY_pubEBayBoard-view",
            route: "",
            platform: "EBAY",
            apiPath: null,
            description: "删除按钮",
            parentKey: "EBAY_pubEBayBoard",
            buttonType: "delete"
          }],
        },
        {
          id: null,
          typeStyle: "page",
          key: "PLAT_EBAY_componentBoard",
          route: baseRoute + "/componentBoard",
          platform: "EBAY",
          apiPath: null,
          description: "组件模板",
          parentKey: "EBAY_eBayBoard",
          children: [{
            id: null,
            typeStyle: "btn",
            key: "EBAY_componentBoard-view",
            route: "",
            platform: "EBAY",
            apiPath: null,
            description: "控制当前页面能否查看",
            parentKey: "PLAT_EBAY_componentBoard",
            buttonType: "view"
          }, {
            id: null,
            typeStyle: "btn",
            key: "EBAY_componentBoard-view",
            route: "",
            platform: "EBAY",
            apiPath: null,
            description: "编辑按钮",
            parentKey: "EBAY_componentBoard",
            buttonType: "edit"
          }, {
            id: null,
            typeStyle: "btn",
            key: "EBAY_componentBoard-view",
            route: "",
            platform: "EBAY",
            apiPath: null,
            description: "删除按钮",
            parentKey: "EBAY_componentBoard",
            buttonType: "delete"
          }],
        },
      ]
    },
    // {
    //   id: null,
    //   icon: "marketing",
    //   key: "EBAY_eBayMarketing",
    //   route: "",
    //   platform: "EBAY",
    //   apiPath: null,
    //   description: "营销",
    //   typeStyle: "menu",
    //   parentKey: "EBAY_eBay",
    //   children: [{
    //     id: null,
    //     typeStyle: "page",
    //     key: "EBAY_eBayDiscount",
    //     route: baseRoute + "/eBayDiscount",
    //     platform: "EBAY",
    //     apiPath: null,
    //     description: "eBay打折",
    //     parentKey: "EBAY_eBayMarketing",
    //     children: [{
    //       id: null,
    //       typeStyle: "btn",
    //       key: "EBAY_eBayDiscount-view",
    //       route: "",
    //       platform: "EBAY",
    //       apiPath: null,
    //       description: "控制当前页面能否查看",
    //       parentKey: "EBAY_eBayDiscount",
    //       buttonType: "view"
    //     }],
    //   },
    //   {
    //     id: null,
    //     typeStyle: "page",
    //     key: "EBAY_standardAdvertising",
    //     route: baseRoute + "/standardAdvertising",
    //     platform: "EBAY",
    //     apiPath: null,
    //     description: "标准广告(PLS)",
    //     parentKey: "EBAY_eBayMarketing",
    //     children: [{
    //       id: null,
    //       typeStyle: "btn",
    //       key: "EBAY_standardAdvertising-view",
    //       route: "",
    //       platform: "EBAY",
    //       apiPath: null,
    //       description: "控制当前页面能否查看",
    //       parentKey: "EBAY_standardAdvertising",
    //       buttonType: "view"
    //     }],
    //   },
    //   {
    //     id: null,
    //     typeStyle: "page",
    //     key: "EBAY_advancedAdvertising",
    //     route: baseRoute + "/advancedAdvertising",
    //     platform: "EBAY",
    //     apiPath: null,
    //     description: "高级广告(PLA)",
    //     parentKey: "EBAY_eBayMarketing",
    //     children: [{
    //       id: null,
    //       typeStyle: "btn",
    //       key: "EBAY_advancedAdvertising-view",
    //       route: "",
    //       platform: "EBAY",
    //       apiPath: null,
    //       description: "控制当前页面能否查看",
    //       parentKey: "EBAY_advancedAdvertising",
    //       buttonType: "view"
    //     }],
    //   }
    //   ]
    // },
    // {
    //   id: null,
    //   icon: "publication",
    //   key: "EBAY_ebayPublishlLog",
    //   route: "",
    //   platform: "EBAY",
    //   apiPath: null,
    //   description: "刊登日志",
    //   typeStyle: "menu",
    //   parentKey: "EBAY_eBay",
    //   children: [{
    //     id: null,
    //     typeStyle: "page",
    //     key: "PLAT_EBAY_ebayReleaseLog",
    //     route: baseRoute + "/ebayReleaseLog",
    //     platform: "EBAY",
    //     apiPath: null,
    //     description: "发布日志",
    //     parentKey: "EBAY_ebayPublishlLog",
    //     children: [{
    //       id: null,
    //       typeStyle: "btn",
    //       key: "EBAY_ebayReleaseLog-view",
    //       route: "",
    //       platform: "EBAY",
    //       apiPath: null,
    //       description: "控制当前页面能否查看",
    //       parentKey: "PLAT_EBAY_ebayReleaseLog",
    //       buttonType: "view"
    //     }],
    //   },
    //   {
    //     id: null,
    //     typeStyle: "page",
    //     key: "PLAT_EBAY_ebayUpdateLog",
    //     route: baseRoute + "/ebayUpdateLog",
    //     platform: "EBAY",
    //     apiPath: null,
    //     description: "更新日志",
    //     parentKey: "EBAY_ebayPublishlLog",
    //     children: [{
    //       id: null,
    //       typeStyle: "btn",
    //       key: "EBAY_ebayUpdateLog-view",
    //       route: "",
    //       platform: "EBAY",
    //       apiPath: null,
    //       description: "控制当前页面能否查看",
    //       parentKey: "PLAT_EBAY_ebayUpdateLog",
    //       buttonType: "view"
    //     }],
    //   },

    //   ]
    // }
  ],
}]