// 客服通用工具
const baseRoute = '/multiplatform-web';
export default {
  key: "PLAT_customerTools",
  id: null,
  platform: 'PLAT',
  typeStyle: "menu",
  icon: "generalTools",
  route: '',
  apiPath: null,
  description: "客服通用工具",
  name: '客服通用工具',
  parentKey: "PLAT_customer",
  isMultiMenu: true,
  children: [
    {
      key: "PLAT_customerTools_platForm",
      id: null,
      platform: 'PLAT',
      typeStyle: "menu",
      icon: '',
      route: '',
      apiPath: null,
      description: "多平台",
      name: '多平台',
      parentKey: "PLAT_customerTools",
      isMultiMenu: true,
      children: [
        {
          key: "PLAT_customerTools_commonWords",
          id: null,
          platform: 'PLAT',
          typeStyle: "page",
          icon: '',
          route: baseRoute + "/commonWords",
          apiPath: null,
          description: "常用语",
          name: '常用语',
          parentKey: "PLAT_customerTools_platForm",
          isMultiMenu: true,
        },
        {
          key: "PLAT_customerTools_allocationRules",
          id: null,
          platform: 'PLAT',
          typeStyle: "page",
          icon: '',
          route: baseRoute + "/allocationRules",
          apiPath: null,
          description: "消息分配规则",
          name: '消息分配规则',
          parentKey: "PLAT_customerTools_platForm",
          isMultiMenu: true,
        },
        {
          key: "PLAT_customerTools_classificationLabel",
          id: null,
          platform: 'PLAT',
          typeStyle: "page",
          icon: '',
          route: baseRoute + "/classificationLabel",
          apiPath: null,
          description: "消息分类标签",
          name: '消息分类标签',
          parentKey: "PLAT_customerTools_platForm",
          isMultiMenu: true,
        },
        {
          key: "PLAT_customerTools_treatmentAging",
          id: null,
          platform: 'PLAT',
          typeStyle: "page",
          icon: '',
          route: baseRoute + "/treatmentAging",
          apiPath: null,
          description: "消息处理时效",
          name: '消息处理时效',
          parentKey: "PLAT_customerTools_platForm",
          isMultiMenu: true,
        },
        {
          key: "PLAT_customerTools_evaluationLabel",
          id: null,
          platform: 'PLAT',
          typeStyle: "page",
          icon: '',
          route: baseRoute + "/evaluationLabel",
          apiPath: null,
          description: "评价标签",
          name: '评价标签',
          parentKey: "PLAT_customerTools_platForm",
          isMultiMenu: true,
        },
      ]
    },
  ]
}
